### ISSUE TITLE
Decimal values in HEX

### ISSUE THREAD

**Issue by hadasj** [ivos/lightair#1]
Hi Ivo!

It would be nice to enter big integer value in HEX, for example:
  <ciszmena id="@any" idsubjekt="1000"  idevidence="2" typsubjektu="P" typzmeny="I"
            aifo="YCYlNrg9epsC4jsr6RVNYC4=" polozky="0x1002000" uid="12918" ts="@timestamp"/>

where 0x1002000 is integer value in HEXa representation.
Now it is not posibble - it uses dbunit DataType.typeCast from string to BigInteger, but dbunit expects number in decimal format..

Honza Hadaš

**Comment by ivos** [comment]
Hi Honzo,
I assume this concerns whole numbers (ints, longs, etc.). If it is clear from the context that we are dealing with a whole number (as opposed to a varchar, for example) then supporting alternative notations, like e.g. hexadecimal, sounds good. I am all in. Pull request is welcome.
Thanks. Ivo

**Comment by hadasj** [comment]
I have made pull request for the case i exactly need - HEX + BigInteger.
It is useful for expressing bits in logs in HEX (alone bits are in binary/hex better visible).

**Comment by ivos** [comment]
Will have a look at it. Basically, I have two issues:
- I prefer Integer.decode to have a generic solution for hexa (#, 0x, 0X) and octal (0) representations.
- I believe the if should be primarily based on the data type being integer (or big integer) - that's the decision point (as I tried to express above), only then will the decode be applied no matter whether the value itself starts with any special chars.

If you care about changing it, I will appreciate. Otherwise I will try to consolidate it myself. Thanks!

**Comment by ivos** [comment]
Release 2.8.0 available.
